name = "worker-orsoie-d1"
main = "worker-orsoie-d1.js"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "orsoie"
database_id = "a4b46ac9-7a5f-4731-af86-8dcc0b72808e" 