name = "worker-invitados"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[[d1_databases]]
binding = "DB"
database_name = "orsoie"
database_id = "a4b46ac9-7a5f-4731-af86-8dcc0b72808e"

[vars]
EVENT_CODE = "20250712_mariaycarlos" 